PRAGMA Foreign_Keys = True;

DROP TABLE loan;
DROP TABLE item;
DROP TABLE member;

CREATE TABLE member (
ID INTEGER PRIMARY KEY,
Name TEXT NOT NULL,
Email TEXT
);

CREATE TABLE item (
ID INTEGER PRIMARY KEY,
Name TEXT NOT NULL,
Description TEXT NOT NULL,
OwnerID INTEGER NOT NULL REFERENCES member(ID),
Price NUMERIC,
Condition TEXT,
DateRegistered TEXT
);

CREATE TABLE loan (
ID INTEGER PRIMARY KEY,
ItemID INTEGER NOT NULL REFERENCES item(ID),
BorrowerID INTEGER NOT NULL REFERENCES member(ID),
DateBorrowed TEXT NOT NULL,
DateReturned TEXT
);